### ISSUE TITLE
Not running properly

### ISSUE THREAD

**Issue by RenzukaCtone** [dxAugust/VC-MP#1]
When I directly used the apk from the source and replaced main.scm, the game only have a scene like vcmp.
Then I get the libvcmp.so from ndk, the time text turn to "VC:MP" and the touch of the game was not working when I started the game.

**Comment by fet1sov** [comment]
Hi, sorry I was inactive on GitHub for a while.
Could please explain issue little bit more expanded.

**Comment by fet1sov** [comment]
Sure, project is in undone stage and have a bunch of issues. So really I'm really sorry if you got one of them
main.scm deleting pedestrians and other pickups on the map, touches should work.
Make sure you are not using the GTA VC 2.0 version.

**Comment by fet1sov** [comment]
Also try to comment whole scripting stuff (All dependencies to the **scripting.h** class), I think the problem inside of it

**Comment by Dukinja** [comment]
Maybe the hooks make this happen
